### PR TITLE
utMath.h general tweaks

### PR DESCRIPTION
**Pull request by siavashserver**
- Performed general tweaks and clean ups on `utMath.h`
- Eliminated a few divisions and replaced them with multiplies
- Optimized `determinant()` and `inverted()` functions to generate smaller code with less dependency chains resulting in out of order execution on supporting hardware

### CODE REVIEW

**Comment by attilaz** [comment]
thanks for this patch.
 I tried to view the changes but it seems like the whole file is different, maybe because line ending conversion. Could you post a version that has the same tab/space/line ending that the original version? 
Maybe I messed up something when uploaded the original sources. I'm on windows 7/ visual studio 2008. what environment are you using?

**Comment by siavashserver** [comment]
Hello, I'm using QtCreator on Arch Linux. QtCreator automatically cleans white spaces and auto indents on exit, during that time, _tabs_ were converted to _spaces_ and I didn't noticed that before committing.

Now it is ready for review ^^

**Comment by siavashserver** [comment]
I think at some point we need to get rid of all white spaces in Horde3Ds source code and perform a cleanup.

**Comment by siavashserver** [comment]
I can provide a much cleaner version, and easier to review version without any changes to source code spacing and indenting this evening.

**Comment by attilaz** [comment]
I was thinking about the usage of branches on github. I would like to keep the "master" in sync with the svn version. So I only apply changes from svn. We should have different branches with features, something like "Math optimization" branch in this case. After code reviews we could ask Volker and Marciano to check them and they decide if it should be merged into the svn. after that I will merge it into the master. 
Is it ok for you? 
I can give you collaborator rights if you would like to work on this, OR You can do the proposed changes in your fork. Or I can create one branch for you.

**Comment by siavashserver** [comment]
Yes, I think it is better to keep the master branch in sync with SVN repository too. I like to work on many different ideas and have multiple branches, so I gladly accept your offer to become one of collaborators on this repository :-)

**Comment by siavashserver** [comment]
Thank you @attilaz .

**Pull request closed without merging**
